<?php
/**
 * Settings loader + writer. Reads `config/settings.default.php` then merges
 * the gitignored `config/settings.local.php` on top.
 *
 * Saving from the admin UI writes back only to `settings.local.php`.
 */
class Settings
{
    private static $cache = null;

    private static function paths()
    {
        $root = dirname(__DIR__);
        return [
            'default' => $root . '/config/settings.default.php',
            'local'   => $root . '/config/settings.local.php',
        ];
    }

    public static function all()
    {
        if (self::$cache !== null) return self::$cache;
        $p = self::paths();
        $defaults = is_file($p['default']) ? (require $p['default']) : [];
        $local    = is_file($p['local'])   ? (require $p['local'])   : [];
        self::$cache = array_merge($defaults, is_array($local) ? $local : []);
        return self::$cache;
    }

    public static function get($key, $fallback = null)
    {
        $all = self::all();
        return array_key_exists($key, $all) ? $all[$key] : $fallback;
    }

    /**
     * Persist a partial array of overrides to settings.local.php.
     * Returns [bool $ok, string $error_or_path].
     */
    public static function save(array $patch)
    {
        $p = self::paths();
        $localDir = dirname($p['local']);
        if (!is_dir($localDir)) {
            if (!@mkdir($localDir, 0775, true)) {
                return [false, "Could not create $localDir"];
            }
        }
        $current = is_file($p['local']) ? (require $p['local']) : [];
        if (!is_array($current)) $current = [];
        $merged = array_merge($current, $patch);

        $body = "<?php\n// Generated by Eventra admin Settings page. Do not edit by hand unless you know what you're doing.\n// THIS FILE IS GITIGNORED — your keys are never committed.\nreturn " . var_export($merged, true) . ";\n";
        $bytes = @file_put_contents($p['local'], $body, LOCK_EX);
        if ($bytes === false) {
            return [false, "Could not write " . $p['local'] . " — check folder permissions."];
        }
        self::$cache = null;
        return [true, $p['local']];
    }

    public static function isSupabaseReady()
    {
        $s = self::all();
        return !empty($s['use_supabase'])
            && !empty($s['supabase_url'])
            && (!empty($s['supabase_anon']) || !empty($s['supabase_service']));
    }

    public static function maskKey($k)
    {
        if (!$k) return '';
        $len = strlen($k);
        if ($len <= 12) return str_repeat('•', $len);
        return substr($k, 0, 6) . str_repeat('•', max(4, $len - 12)) . substr($k, -6);
    }
}
