<?php
/**
 * Default settings for Eventra. Do NOT edit this file directly for your own keys —
 * they are saved to `config/settings.local.php` (gitignored) from the admin Settings page.
 *
 * If `settings.local.php` exists it overrides this file at runtime.
 */
return [
    // Master switch. When true and Supabase keys are configured, data reads/writes go to Supabase.
    // When false (default) the app uses local MySQL via classes/db1.php.
    'use_supabase'    => false,

    // Supabase project URL, e.g. https://abcdefghij.supabase.co
    'supabase_url'    => '',

    // Anonymous (public) API key — safe for client-side use, respects RLS.
    'supabase_anon'   => '',

    // Service-role key — bypasses RLS. Treat like a password.
    // Only enter this in a trusted local/admin context.
    'supabase_service'=> '',

    // Local MySQL connection (used when use_supabase = false).
    'mysql_host'      => 'localhost',
    'mysql_user'      => 'root',
    'mysql_pass'      => '',
    'mysql_db'        => 'cems',
];
